{% set version = "7.3.0" %}

package:
  name: cx_oracle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Oracle/cx_Oracle-{{ version }}.tar.gz
  sha256: 2e0da54e948b55e5c75fab14b391d58aa8b9be1eddfd9ec9a8a0e500bc8bfc7e
  patches:
    - 0001-Add-macro-for-isnan-msvc-2008.patch  # [win and vc<14]

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - cx_Oracle

about:
  home: https://oracle.github.io/python-cx_Oracle
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python interface to Oracle
  doc_url: https://cx-oracle.readthedocs.io/
  dev_url: https://github.com/oracle/python-cx_Oracle

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - nicoddemus
