{% set version = "8.2.1" %}

package:
  name: cx_oracle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cx_Oracle/cx_Oracle-{{ version }}.tar.gz
  sha256: 12e7e913a7a10fd8caafb9855e6703a601b7dd5cc596fcd489d0ac9529608b6c
  patches:
    - 0001-Add-macro-for-isnan-msvc-2008.patch  # [win and vc<14]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - cx_Oracle

about:
  home: https://oracle.github.io/python-cx_Oracle
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python interface to Oracle
  doc_url: https://cx-oracle.readthedocs.io/
  dev_url: https://github.com/oracle/python-cx_Oracle

extra:
  recipe-maintainers:
    - lincrosenbach
    - kfasolin
    - nicoddemus
